### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zetaab** [aquasecurity/go-dep-parser#98]
```
goroutine 23145 [running]:
github.com/aquasecurity/go-dep-parser/pkg/golang/mod.Parse({0x7fd5e5e7f3d0, 0xc010539f70})
    /runner/_work/image-scanner/image-scanner/vendor/github.com/aquasecurity/go-dep-parser/pkg/golang/mod/parse.go:29 +0x13c
github.com/aquasecurity/fanal/analyzer/language.Analyze({0x28b10eb, 0x5}, {0xc009ec0500, 0x4f}, {0x7fd5e5e7f3d0?, 0xc010539f70?}, 0x5d3f38?)
    /runner/_work/image-scanner/image-scanner/vendor/github.com/aquasecurity/fanal/analyzer/language/analyze.go:16 +0x68
github.com/aquasecurity/fanal/analyzer/language/golang/mod.gomodAnalyzer.Analyze({}, {0x26b57a0?, 0x0?}, {{0x0, 0x0}, {0xc009ec0500, 0x4f}, {0x2efe778, 0xc000bfad20}, {0x7fd5e5e7f3a0, ...}, ...})
    /runner/_work/image-scanner/image-scanner/vendor/github.com/aquasecurity/fanal/analyzer/language/golang/mod/mod.go:39 +0xc5
github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile.func1({0x2ef93e8, 0x4520270}, {0x2efaed0?, 0xc010539f70})
    /runner/_work/image-scanner/image-scanner/vendor/github.com/aquasecurity/fanal/analyzer/analyzer.go:258 +0x253
created by github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile
    /runner/_work/image-scanner/image-scanner/vendor/github.com/aquasecurity/fanal/analyzer/analyzer.go:253 +0x3d8
```

https://github.com/aquasecurity/go-dep-parser/blob/main/pkg/golang/mod/parse.go#L29

ping @jerbob92 you need to check `modFileParsed.Go != nil`

**Comment by jerbob92** [comment]
Thanks! That code was made by @knqyf263 though. 
Fix looks good to me

**Comment by knqyf263** [comment]
Thanks. Looks good.
